apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base
  - claro-ai-crm-config.configmap.yaml
  - claro-ai-crm-db.sealedsecret.yaml
  - claro-ai-crm-env.sealedsecret.yaml
