apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: claro-ai-crm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: apps
  source:
    repoURL: https://github.com/dev-claroenergy/dev-server-gitops.git
    targetRevision: HEAD
    path: apps/claro-ai-crm/overlays/home-server
  destination:
    server: https://kubernetes.default.svc
    namespace: claro-ai-crm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
