apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: claro-ai-crm
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.claro-ai-crm.test/claro-ai-crm/api:dev-v0.0.2
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: claro-ai-crm-config
            - secretRef:
                name: claro-ai-crm-env
          env:
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: claro-ai-crm-db
                  key: username
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: claro-ai-crm-db
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: claro-ai-crm
spec:
  selector:
    app: api
  ports:
    - port: 3000
      targetPort: 3000
