apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: claro-ai-crm
  namespace: claro-ai-crm
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - claro-ai-crm.claro-ai-crm.test
      secretName: claro-ai-crm-tls
  rules:
    - host: claro-ai-crm.claro-ai-crm.test
      http:
        paths:
          - path: /me
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: api
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 80
